# Generated by Django 2.2.6 on 2019-10-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('seniority', models.CharField(choices=[('senior', 'Sênior'), ('pleno', 'Pleno'), ('junior', 'Junior')], max_length=7, verbose_name='Senioridade')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número da sprint')),
                ('start_date', models.DateField(verbose_name='Data de início da sprint')),
                ('end_date', models.DateField(verbose_name='Data de finalização da sprint')),
                ('active', models.BooleanField(verbose_name='Sprint ativa?')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, verbose_name='Código no Jira')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('creation_date', models.DateField(verbose_name='Data de criação')),
                ('points', models.PositiveSmallIntegerField(verbose_name='Pontos da história')),
                ('duration', models.DurationField(verbose_name='Duração')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Developer')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('development_area', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('hibrido', 'Hibrido')], max_length=10, verbose_name='Área de desenvolvimento')),
            ],
        ),
        migrations.CreateModel(
            name='StoryTaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Story')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TaskType')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('number',), name='number'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('active',), name='active'),
        ),
    ]
