# Generated by Django 2.2.6 on 2019-11-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('creation_date', models.DateField(verbose_name='Data de criação')),
                ('duration', models.DurationField(verbose_name='Duração')),
                ('code', models.CharField(max_length=7, verbose_name='Código no Jira')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Developer')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprint_bug', to='core.Sprint')),
            ],
        ),
    ]
