# Generated by Django 2.2.6 on 2019-11-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191031_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impedment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateField(verbose_name='Data')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Developer')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprint_impedment', to='core.Sprint')),
            ],
        ),
    ]
