# Generated by Django 2.2.6 on 2019-11-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191104_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprint_storysprint', to='core.Sprint')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_storysprint', to='core.Story')),
            ],
        ),
    ]
