# Generated by Django 2.2.6 on 2019-11-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_storysprint_datamigration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='sprint',
        ),
    ]
