# Generated by Django 2.2.6 on 2019-11-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_story_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Sprint ativa?'),
        ),
    ]
