# Generated by Django 2.2.6 on 2019-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191125_1933'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sprint',
            name='active',
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('active',), name='active'),
        ),
    ]
