# Generated by Django 2.2.6 on 2019-12-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191125_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='initial_points',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (5, 5), (8, 8), (13, 13), (21, 21)], verbose_name='Pontos iniciais da história'),
        ),
    ]
