# Generated by Django 2.2.6 on 2019-12-16 19:01

from django.db import migrations, models


def fill_completed_stories(apps, schema_editor):
    StorySprint = apps.get_model('core', 'StorySprint')
    Story = apps.get_model('core', 'Story')

    completed_stories = Story.objects.filter(completed=True)

    combines_for_update = list()

    for story in completed_stories:
        last_sprint = StorySprint.objects.filter(
            story=story
        ).order_by('sprint__number').last()

        last_sprint.completed = True
        combines_for_update.append(last_sprint)

    StorySprint.objects.bulk_update(combines_for_update, ['completed'])




class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191216_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysprint',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Finalizada?'),
        ),
        migrations.RunPython(fill_completed_stories),
    ]
